### ISSUE TITLE
Add a `byPath` sorter

### ISSUE THREAD

**Issue by eTorAken** [renke/import-sort#3]
Hi @renke,

Our team just found your https://github.com/renke/atom-import-sort project which would probably resolve a lot of issue we are experiencing during our coding reviews.

We would like to implement a custom-style which would:
1. organize by node modules first, then external packages, then relatives file links
2. organize by relative path hierarchy (for relative links), which means links near project root first, links far from project root then
3. organize alphabetically by **path** name

A sample of this pattern:
```js
import fs from 'fs';
import path from 'path';

import Promise from 'bluebird';
import HTTPStatus from 'http-status-codes';

import { router AS primaryRouter } from '../../router.jsx';
import config from '../config.jsx';
import { ping } from './defaultRoute.jsx';
import { index } from './route.jsx';
```

To implement this, we need another sorter than the `byIdentifier`. Do you think a `byPath` or `byPathHierarchy` sorter would be accurate here?

**Comment by renke** [comment]
Hi @eTorAken,

`byPath` and `byPathHierachy` (maybe even something like `byPathDepth`) definitely sound reasonable. Implementing those shouldn't be too hard (similarly to [byIdentifier](https://github.com/renke/import-sort/blob/3888adad1d4e8ad78aa29a4fccea1e86658d6f6c/src/sorter.js#L3)). 

It's probably a good idea to introduce a higher-order function that combines multiple sort function, e.g. something like `sort: combining(byPathDepth, byPath, byIdentifier)`.

Since you mentioned [atom-import-sort](https://github.com/renke/atom-import-sort) I assume you want to use your custom style from within in Atom. Unfortunately, there is currently no way to use a different style using my plugin. What do you think would be a good way to change the style in Atom?

**Comment by eTorAken** [comment]
Hi @renke,

Thanks for your answer.

I think it would be nice to add an option in [atom-import-sort](https://github.com/renke/atom-import-sort) which let the user choose the order of the `combining` function you just mentioned (assuming it is implemented).

What do you think about that?

**Comment by renke** [comment]
Hi @eTorAken 

sorry, for the not so timely answer. No, combining, `byPath` and the like are not currently implemented because I did not yet need them. I would gladly accept any PR in that direction.

Regarding Atom I was thinking about distributing custom styles as own modules, e.g. import-sort-style-etoraken for your personal style, or import-sort-style-company-xyz for your company's preferred style. Similar to plugins in other tools (eslint, babel). Public styles could be distributed (and thus shared) using NPM, but don't need to. They just need to be installed globally or locally, that is, resolvable from the file that is being sorted. Choosing a particular style in Atom would then just be a setting that tells the plugin to use style 'etoraken' or 'company-xyz'. The plugin could even reads this information from a `.sortrc` to allow per-project styles.

What do you think?

**Comment by eTorAken** [comment]
I think that's a good idea, indeed.

**Comment by renke** [comment]
Hi there, I just wanted to say that sorting by path name will land in the next version of import-sort!

**Comment by loewen-uwaterloo** [comment]
Hi @renke came across this and it could be very useful for us once the byPath sort is available.  Do you have an approximate date for when the next version will be available?

**Comment by renke** [comment]
@loewen-uwaterloo I can't give an exact date currently. I am basically writing import-sort from scratch to be flexible in regard to styles and parsers. It will take a while, but I'll let you know.

**Comment by renke** [comment]
I just added a new matcher `isNodeModule` and sorter `dotSegmentCount` which should make it possible to create a style that does what you want. 

The style would probably look like this (haven't tested it yet):

```js
…
{match: isNodeModule, sort: moduleName(naturally)}
{match: isAbsoluteModule, sort: moduleName(naturally)}
{match: isRelativeModule, sort: [dotSegmentCount, moduleName(naturally)]}
…
```
If you specify in more detail what the style should look like, we could probably create an official style that would be included in this repository.

**Comment by loewen-uwaterloo** [comment]
Not sure what the original requester would want, but if I have
file `./x/d/f` with
```
import C from `./c`;
import B from '../a/b';
import D from '../f/d';
import K from '../../a/k';
import J from '../../y/j';
```
the correct sorted order would be
```
import K from '../../a/k';
import B from '../a/b';
import C from `./c`;
import D from '../f/d';
import J from '../../y/j';
```
or basically finding the relative path of each file from the common root and sorting by those relative paths

**Comment by renke** [comment]
I created a new style [import-sort-style-module](https://github.com/renke/import-sort/tree/master/packages/import-sort-style-module) that sorts by modules similar to what @eTorAken described. I hope it's useful to you.

**Comment by eTorAken** [comment]
I may have miss something but I cannot use it right now. Atom throws `Style 'module' not found`.

This is what I've done:
1) Install `atom-import-sort`
2) Set to my `package.json`:
```
  "importSort": {
    ".js, .jsx": {
      "parser": "babylon",
      "style": "module"
    }
  }
```
Did I miss something?

**Comment by renke** [comment]
@eTorAken yes, you should install `npm install --save-dev import-sort-style-module`. I don't want to include those styles with `atom-import-sort` because it's project-specific, that's why you have to install it. Let me know that works for you.

**Comment by eTorAken** [comment]
It is working, thank you a lot! That's exactly what we were looking for!

**Comment by renke** [comment]
I am glad you and your team like it. Actually, I am starting to prefer that style, too. Also, if you find any problem or have suggestions to improve the style, just let me know.
