### ISSUE TITLE
Configurable style for the CLI tool

### ISSUE THREAD

**Issue by fatso83** [renke/import-sort#44]
Seeing as this can be used as a CLI tool, I think it would make sense to also expose the possibility of selecting the sorting style on command line, much in the same sense Mocha does:

- `--styles` would list the available style plugins
- `--style renke` would select that

**Comment by renke** [comment]
Hi @fatso83 

this is not a bad per-se but the problem is that styles have to be installed to be available (to do this we need to look into node_modules to see which styled are installed).

In general it's better specify the style to be used in a configuration file (like package.json) so I will probably not implement this feature right now. Maybe in a later release.

Thanks for your feedback though.
