### ISSUE TITLE
CLI should allow piping from STDIN

### ISSUE THREAD

**Issue by bugeats** [renke/import-sort#86]
This should just work:

    cat file.js | import-sort

It would make editor integrations much easier too.

**Comment by renke** [comment]
This was originally supported but it posed some problems, because we detect what config to use based on the file name / extension which would be unknown when reading from stdin. 

I am happy to accept PRs that implement in way similar to prettier (see https://prettier.io/docs/en/cli.html#stdin-filepath) though.

**Comment by samhh** [comment]
In the meantime, folks may find my shell script wrapper helpful: https://github.com/samhh/dotfiles/commit/ccbed22c9d5e9e9b6a34cec3b545abecfd27dbc1
